name: Trigger auto deployment for anil-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/anil-container-AutoDeployTrigger-a26ecc04-5cb3-4f7f-8ab6-90498f322c71.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANILCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: user36anilcontainerregistry.azurecr.io
          registryUsername: ${{ secrets.ANILCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANILCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: anil-container
          resourceGroup: user36
          imageToBuild: user36anilcontainerregistry.azurecr.io/anil-container:${{ github.sha }}
          
            

     

